name: Publish
on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: "Release Type"
        required: true
        type: choice
        default: "patch"
        options:
          - patch
          - minor
          - major
      releaseChannel:
        description: "Release Channel"
        required: true
        type: choice
        default: stable
        options:
          - stable
          - edge
      publishMarketplace:
        description: "Publish on Visual Studio Marketplace?"
        required: true
        type: choice
        default: "yes"
        options:
          - "yes"
          - "no"
  # push:
  #   branches:
  #     - main
  #     - edge
  #   paths:
  #     - '**'
  #     - '!README.md'
  #     - '!test/**'
  #     - '!.vscode/**'
  #     - '!.gitignore'
  #     - '!.editorconfig'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node version
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install dependencies
        run: npm ci
      - name: Package Extension (pre-release)
        if: inputs.releaseType == 'edge'
        run: npx vsce package -o "./extension.vsix" --pre-release
      - name: Package Extension (stable)
        if: inputs.releaseType == 'stable'
        run: npx vsce package -o "./extension.vsix"
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: extension
          path: ./extension.vsix

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: extension
      - name: Publish to Visual Studio Marketplace
        run: npx vsce publish --packagePath "./extension.vsix" -p ${{ secrets.VSC_MKTP_PAT }}
      - name: Commit and push updated package.json
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add package.json
          git commit -m "update package.json version"
          git push
