name: Publish
on:
  push:
    branches:
      - main
      - edge
    paths-ignore:
      - 'test/**'
      - '.vscode/**'
      - '.gitignore'
      - '.editorconfig'
      - '.eslintrc.json'
      - '.vscodeignore'
      - 'CNAME'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node version
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install dependencies
        run: npm ci
      - name: Set git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Publish to Visual Studio Marketplace as Pre-Release
        if: github.ref == 'refs/heads/edge'
        run: npx vsce publish -p ${{ secrets.VSC_MKTP_PAT }} --pre-release patch
      - name: Publish to Visual Studio Marketplace
        if: github.ref == 'refs/heads/main'
        run: npx vsce publish -p ${{ secrets.VSC_MKTP_PAT }}
      - name: Push updates made by vsce publish
        if: github.ref == 'refs/heads/edge'
        run: git push
