name: Publish

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: "Release Type"
        required: true
        type: choice
        default: "patch"
        options:
          - patch
          - minor
          - major
      releaseChannel:
        description: "Release Channel"
        required: true
        type: choice
        default: stable
        options:
          - stable
          - edge
      publishMarketplace:
        description: "Publish on Visual Studio Marketplace?"
        required: true
        type: choice
        default: "yes"
        options:
          - "yes"
          - "no"
#   push:
#     branches:
#       - main
#       - edge
#     paths:
#       - '**'
#       - '!README.md'
#       - '!test/**'
#       - '!.vscode/**'
#       - '!.gitignore'
#       - '!.editorconfig'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2.4.2
        with:
          fetch-depth: 0
      - name: Setup Node version
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 16
      - name: Cache dependencies
        uses: actions/cache@v2.1.7
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install dependencies
        run: npm ci
      - name: Build Package
        run: npm run build
#       - name: Run Tests
#         uses: GabrielBB/xvfb-action@v1.4
#         with:
#           run: npm test
#           options: "-screen 0 1600x1200x24"
      - name: Get Current Version Number
        run: |
          CURRENT_VERSION=$(cat package.json | jq .version | cut -d'"' -f 2)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
      - name: Compile New Version
        run: |
          RELEASE_VERSION=$(npx semver $CURRENT_VERSION -i patch)
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "Bump to $RELEASE_VERSION"
      - name: Version Package
        run: npm version $RELEASE_VERSION --no-git-tag-version
      - name: Create Git Tag
        uses: satterly/github-tag-action@v1.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.RELEASE_VERSION }}
      - name: Package Extension
        run: npx vsce package --no-git-tag-version --no-update-package-json -o "./extension-$RELEASE_VERSION.vsix"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2.4.1
        with:
          name: extension
          path: ./extension-*.vsix

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2.1.3
        with:
          name: extension
      - name: Publish to Visual Studio Marketplace
        run: npx vsce publish --packagePath "./extension-*.vsix" --no-git-tag-version --no-update-package-json -p ${{ secrets.VSC_MKTP_PAT }}
