name: Publish
on:
  workflow_dispatch:
    inputs:
      releaseChannel:
        description: "Release Channel"
        required: true
        type: choice
        default: edge
        options:
          - stable
          - edge
  # push:
  #   branches:
  #     - main
  #     - edge
  #   paths:
  #     - '**'
  #     - '!README.md'
  #     - '!test/**'
  #     - '!.vscode/**'
  #     - '!.gitignore'
  #     - '!.editorconfig'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node version
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install dependencies
        run: npm ci
      - name: Publish to Visual Studio Marketplace as Pre-Release
        if: inputs.releaseChannel == 'edge'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          npx vsce publish -p ${{ secrets.VSC_MKTP_PAT }} --pre-release patch
      - name: Publish to Visual Studio Marketplace
        if: inputs.releaseChannel == 'stable'
        run: npx vsce publish -p ${{ secrets.VSC_MKTP_PAT }}  patch
      - name: Push updates made by vsce publish
        run: git push
