name: Publish
on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: "Release Type"
        required: true
        type: choice
        default: "patch"
        options:
          - patch
          - minor
          - major
      releaseChannel:
        description: "Release Channel"
        required: true
        type: choice
        default: stable
        options:
          - stable
          - edge
      publishMarketplace:
        description: "Publish on Visual Studio Marketplace?"
        required: true
        type: choice
        default: "yes"
        options:
          - "yes"
          - "no"
  # push:
  #   branches:
  #     - main
  #     - edge
  #   paths:
  #     - '**'
  #     - '!README.md'
  #     - '!test/**'
  #     - '!.vscode/**'
  #     - '!.gitignore'
  #     - '!.editorconfig'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
      - name: Setup Node version
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
      - name: Cache dependencies
        uses: actions/cache@v3.2.6
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install dependencies
        run: npm ci
      - name: Build Package
        run: npm run build
#       - name: Run Tests
#         uses: GabrielBB/xvfb-action@v1.4
#         with:
#           run: npm test
#           options: "-screen 0 1600x1200x24"
      - name: Package Extension
        run: npx vsce package -o "./extension.vsix"
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: extension
          path: ./extension.vsix

#   publish:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Download Artifact
#         uses: actions/download-artifact@v2.1.3
#         with:
#           name: extension
#       - name: Publish to Visual Studio Marketplace
#         run: |
#           if [ "${{ github.event.inputs.releaseChannel }}" == "edge" ]; then
#             npx vsce publish --packagePath "./extension.vsix" -p ${{ secrets.VSC_MKTP_PAT }} --tag next --increment "${{ github.event.inputs.releaseType }}"
#           else
#             npx vsce publish --packagePath "./extension.vsix" -p ${{ secrets.VSC_MKTP_PAT }} --increment "${{ github.event.inputs.releaseType }}"
#           fi
#       - name: Commit and push updated package.json
#         run: |
#           git config --global user.name "GitHub Actions"
#           git config --global user.email "actions@github.com"
#           git add package.json
#           git commit -m "Update package.json version"
#           git push
